### ISSUE TITLE
Git error

### ISSUE THREAD

**Issue by baeharam** [bparrishMines/mlkit_demo#7]
I saw issued git error but I can't solve by this.

```
firebase_ml_vision:
    git:
      url: git://github.com/bparrishMines/plugins.git
      path: packages/firebase_ml_vision
      ref: mlkit_android_2
  camera:
    git:
      url: git://github.com/bparrishMines/plugins.git
      path: packages/camera
      ref: camera_android_2
```

> [mlkit_demo] flutter packages get
> Waiting for another flutter command to release the startup lock...
> Running "flutter packages get" in mlkit_demo...                 
> Git error. Command: git rev-list --max-count=1 camera_android_2
> fatal: ambiguous argument 'camera_android_2': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> pub get failed (69) -- attempting retry 1 in 1 second...
> Git error. Command: git rev-list --max-count=1 camera_android_2
> fatal: ambiguous argument 'camera_android_2': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> pub get failed (69) -- attempting retry 2 in 2 seconds...
> Git error. Command: git rev-list --max-count=1 camera_android_2
> fatal: ambiguous argument 'camera_android_2': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> pub get failed (69) -- attempting retry 3 in 4 seconds...
